PREFIX eau: <https://w3id.org/eautonome/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?sensor ?slope ?r2 WHERE {
  ?sensor a ?sensorClass .
  ?sensorClass rdfs:subClassOf* sosa:Sensor .
  ?sensor eau:hasCalibrationSlope ?slope ;
          eau:hasCalibrationR2 ?r2 .
}
ORDER BY ?sensor
